variables:
  environment: prod
  serviceName: hrithviksood.me
  awsPrefix: aws-prefix
  awsRoleName: aws-role-name
  awsRegion: ap-southeast-2
  awsProvisionedConcurrencyLow: 1
  awsProvisionedConcurrencyHigh: 5
  awsProvisionedConcurrencyMaxCapacity: 20
  awsHasProvisionedConcurrencyEnabled: true
  awsApiGatewayPublic: false
  subnetIdA: 'subnet-a'
  subnetIdB: 'subnet-b'
  subnetIdC: 'subnet-c'
  awsP90AlertThreshold: 5500
  awsP95AlertThreshold: 7000
  awsP99AlertThreshold: 10000
  aws5xxAlertThreshold: 1
