parameters:
  - name: serviceDir
    type: string
    default: $(System.DefaultWorkingDirectory)
stages:
  - stage: unit_tests
    displayName: Unit Tests
    dependsOn: []
    jobs:
    - job: unit_testing
      displayName: Unit Tests
      steps:
        - task: NodeTool@0
          displayName: Install Node
          inputs:
            versionSpec: '14.x'

        - task: Npm@1
          displayName: Install Dependencies
          inputs:
            command: ci

        - task: Npm@1
          displayName: Lint
          inputs:
            command: custom
            customCommand: run lint

        - task: Npm@1
          displayName: Run unit tests
          inputs:
            command: custom
            customCommand: run test

        - task: PublishTestResults@2
          displayName: Publish Unit Test Results
          inputs:
            testRunTitle: unit-tests
            testResultsFiles: '${{ parameters.serviceDir }}/reports/unit-test-report.xml'
            failTaskOnFailedTests: true
          #condition: and(succeededOrFailed(), eq(variables['serviceChange'], 'true'))

        - task: PublishPipelineArtifact@1
          displayName: "Publish Artifact unit-test-report.xml"
          inputs:
            targetPath: ${{ parameters.serviceDir }}/reports/unit-test-report.xml
            artifactName: UnitTestReport
